on:
  workflow_dispatch: {}
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install APT packages
        run: sudo apt install python3 python3-yaml

      - name: Run tests
        run: ./test.bash

      - name: Clone target repository
        run: git clone https://github.com/yanboyang713/Meta-Scientific-repository.git meta-scientific-repository

      - name: Inspect restored failed build record
        continue-on-error: true
        run: cat meta-scientific-repository/failed-build-records/meta-scientific-pacman-packages.yaml

      - name: Build pacman packages
        if: steps.should_deploy.outputs.should_deploy == 'true'
        uses: pacman-repo-builder/action@0.0.0-rc.62
        with:
          command: build-pacman-repo build

      - name: Inspect changed failed build record
        continue-on-error: true
        run: cat meta-scientific-repository/failed-build-records/meta-scientific-pacman-packages.yaml

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'meta-scientific-repository'
          destination-github-username: 'yanboyang713'
          destination-repository-name: 'Meta-Scientific-repository'
          user-email: yanboyang713@gmail.com
          target-branch: main